### PR TITLE
Update status codes and

### PR DESCRIPTION
**Pull request by Hellowlol**
add status with the status string, raw access to chargerOpmode is now possible.

This will be a breaking change but i think the status codes are better, especially with the updated reason for no current as you get more info about that is happening. 

I also wanted to not overwrite the chargerOpmode so this is still a int and status is the string.

### CODE REVIEW

**Comment by fondberg** [comment]
I think it looks good! Do you want to join us in the discord channel where we have a lot of activity? We are 4 main devs atm but are always looking for more

**Comment by Hellowlol** [comment]
Sure

**Comment by fondberg** [comment]
Here the channel https://discord.gg/3e6zxR

**Comment by fondberg** [comment]
Lets make them lowercase and then merge this and right after create a PR to easee_hass which bumps the major version and shows it is a breaking change.

**Comment by astrandb** [comment]
I haven't been diving into details in the code here so perhaps it is already taken care of, but please make sure that new, unknown integer codes are handles properly, e.g. mapped to "unknown_status_##".

**Review by fondberg — APPROVED** [review]

**Pull request merged**
